# JVM args for Gradle daemon
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# Only keep the module you are working on when building from the IDE to speed up
android.nonTransitiveRClass=true

# Parallelize + cache builds for faster iteration
org.gradle.parallel=true
org.gradle.caching=true

# KSP
ksp.useKSP2=false
